_target_: torch.nn.Sequential
_args_:
  - _target_: collections.OrderedDict

    differentiate_TS:
      _target_: vital.models.layers.Lambda
      fn:
        _target_: didactic.models.time_series.differentiate_ts
        _partial_: True
      order: 1
      
    # expand_feat_dim:
    #   _target_: vital.models.layers.Lambda
    #   fn:
    #     _target_: torch.unsqueeze
    #     _partial_: True
    #   dim: -1

    # downsampling:
    #   _target_: didactic.models.layers.TS_Patching
    #   in_features: 1
    #   out_features: 1
    #   kernel_size: 16
    #   stride: 8
    #   padding: 1

    # squeeze_feat_dim:
    #   _target_: vital.models.layers.Lambda
    #   fn:
    #     _target_: torch.squeeze
    #     _partial_: True
    #   dim: -1
    
    linear_embedding:
      _target_: torch.nn.Linear
      in_features: ${task.time_series_tokenizer.resample_dim}
      out_features: ${task.embed_dim}