_target_: torch.nn.Sequential
_args_:
  - _target_: collections.OrderedDict

    differentiate_TS:
      _target_: vital.models.layers.Lambda
      fn:
        _target_: didactic.models.time_series.differentiate_ts
        _partial_: True
      order: 1
      
    expand_feat_dim:
      _target_: vital.models.layers.Lambda
      fn:
        _target_: torch.unsqueeze
        _partial_: True
      dim: -1

    # it is important to not downsample too much because the convolution will discard the last position
    downsampling:
      _target_: didactic.models.layers.TS_Patching
      in_features: 1
      out_features: 1
      kernel_size: 16
      stride: 8
      padding: 1

    upsampling:
      _target_: torch.nn.Linear
      in_features: 1
      out_features: ${task.embed_dim}

    # positional_encoding:
    #   _target_: didactic.models.time_series.TimeSeriesPositionalEncoding
    #   n_positions: 7 # the last position is discarded because of the convolution
    #   d_model: ${task.embed_dim}
    positional_encoding:
      _target_: didactic.models.layers.PositionalEncoding
      sequence_len: 7 #${task.time_series_tokenizer.resample_dim}
      d_model: ${task.embed_dim}


    transformer_encoder:
      _target_: torch.nn.TransformerEncoder
      num_layers: 1

      norm:
        _target_: torch.nn.LayerNorm
        normalized_shape: (7, ${task.embed_dim})

      encoder_layer:
        _target_: torch.nn.TransformerEncoderLayer
        d_model: ${task.embed_dim}
        nhead: 4
        dim_feedforward: ${task.embed_dim}
        dropout: 0.3
        activation: relu
        batch_first: True
        norm_first: False
