_target_: didactic.models.baselines.ConcatMLPDecoupling2FTs

tabular_unimodal_encoder: ${tabular_unimodal_encoder}
ts_unimodal_encoder: ${ts_unimodal_encoder}
n_tabular_attrs: ${n_tabular_attrs}
n_mlp_layers: 2
d_token: ${task.embed_dim}
dropout: 0.1